<?php

/* @var $this Mage_Customer_Block_Widget_Name */
?>
<div class="form-group field name-firstname" style="position: static;">
    <label for="<?php echo $this->getFieldId('firstname')?>" class="required"><?php echo $this->getStoreLabel('firstname') ?></label>
    <input type="text" id="<?php echo $this->getFieldId('firstname')?>" name="<?php echo $this->getFieldName('firstname')?>" value="<?php echo $this->escapeHtml($this->getObject()->getFirstname()) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->getStoreLabel('firstname')) ?>" maxlength="255" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('firstname') ?> form-control" placeholder="Enter First Name" autocomplete="off" <?php echo $this->getFieldParams() ?> />
    <p class="help-block"></p>
</div>
<div class="form-group field name-lastname" style="position: static;">
    <label for="<?php echo $this->getFieldId('lastname')?>" class="required"><?php echo $this->getStoreLabel('lastname') ?></label>
    <input type="text" id="<?php echo $this->getFieldId('lastname')?>" name="<?php echo $this->getFieldName('lastname')?>" value="<?php echo $this->escapeHtml($this->getObject()->getLastname()) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->getStoreLabel('lastname')) ?>" maxlength="255" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('lastname') ?> form-control" placeholder="Enter Last Name" autocomplete="off" <?php echo $this->getFieldParams() ?> />
</div>

