<?php
    /** @var  $newsItem */
    $newsItem = $this->getNewsItem();
?>
<tr data-id="<?=$newsItem->getNewsId()?>" class="news-data">
    <td><?=$newsItem->getNewsId()?></td>
    <td><?=$newsItem->getName()?></td>
    <td><?=$newsItem->getDescription()?></td>
    <td><?=Mage::helper('core')->formatDate($newsItem->getCreatedAt(), 'yyyy-MM-dd')?></td>
    <td><?=Mage::helper('core')->formatDate($newsItem->getUpdatedAt(), 'yyyy-MM-dd')?></td>
    <td><?=$this->getYesNoOption($newsItem->getIsActive())?></td>
    <td><?=$newsItem->getEmail()?></td>
    <td class="action">
        <button data-id="<?=$newsItem->getNewsId()?>" class="news-delete btn-xs btn-danger">X</button>
        <button data-id="<?=$newsItem->getNewsId()?>" class="news-edit btn-xs btn-warning" style="padding: 0px 50px 0px 50px;">edit</button>
    </td>
    <script type="text/javascript">
        jQuery("button[data-id=<?=$newsItem->getNewsId()?>].news-delete").on('click', function (element) {
            if (confirm('Are you sure to delete?')) {
                jQuery.ajax({
                    url: "<?=$this->getUrl('jaro_myscript/ajax_news/delete')?>",
                    type: 'POST',
                    data: {id: "<?=$newsItem->getNewsId()?>"},
                    dataType: 'json',
                    success: function (data) {
                        console.log(data);
                        if (data.status == 'OK') {
                            window.location = "<?=$this->getUrl('jaro_myscript/news/index')?>";
                        }
                    }
                });
            }
        });
        jQuery("button[data-id=<?=$newsItem->getNewsId()?>].news-edit").on('click', function (element) {
            jQuery.ajax({
                url: "<?=$this->getUrl('jaro_myscript/ajax_news/edit')?>",
                type: 'POST',
                data: {id: "<?=$newsItem->getNewsId()?>"},
                dataType: 'json',
                success: function (data) {
                    if (data.status == 'OK') {
                        jQuery("tr[data-id=<?=$newsItem->getNewsId()?>]").html(data.html);
                    }
                }
            });
        });
    </script>
</tr>