<?php
/** @var Jaro_MyScript_Block_News $this */
$parameters = $this->getRequest()->getParams();
$news = $this->getCustomizedCollection($parameters);
$limit = isset($parameters['limit']) ? $parameters['limit'] : '';
if (!empty($limit)) {
    $this->setPagerHtml($news, $limit);
} else {
    $this->setPagerHtml($news);
}
?>
<div class="page-title">
    <h1><?= Mage::helper('jaro_myscript')->__('News List') ?></h1>
</div>

<div class="row">
    <div class="btn-group-toggle col-md-12" data-toggle="buttons">
        <label class="btn btn-primary">
            <input id="news-add" type="checkbox" checked autocomplete="off"> Add New Item
        </label>
    </div>
    <script type="text/javascript">
        jQuery(function () {
            jQuery('#news-add').change(function() {
                if (jQuery(this).prop('checked')) {
                    jQuery("#news-add-form-section").show();
                } else {
                    jQuery("form#form-add")[0].reset();
                    jQuery("#news-add-form-section").hide();
                }
            })
        });
    </script>
</div>
<br>
<div id="news-add-form-section" class="row" style="display:none;">
    <div class="col-md-12">
        <form id="form-add" action="<?=$this->getUrl('jaro_myscript/news/add')?>" method="post">
            <table class="table">
                <thead class="thead-light">
                    <tr>
                        <th><?=Mage::helper('jaro_myscript')->__('ID')?></th>
                        <th><?=Mage::helper('jaro_myscript')->__('Name')?></th>
                        <th><?=Mage::helper('jaro_myscript')->__('Description')?></th>
                        <th><?=Mage::helper('jaro_myscript')->__('Created At')?></th>
                        <th><?=Mage::helper('jaro_myscript')->__('Updated At')?></th>
                        <th><?=Mage::helper('jaro_myscript')->__('Active')?></th>
                        <th><?=Mage::helper('jaro_myscript')->__('Author')?></th>
                        <th><?=Mage::helper('jaro_myscript')->__('Action')?></th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <?=$this->getChildHtml('news.form.row')?>
                    </tr>
                </tbody>
            </table>
        </form>
    </div>
</div>
<?php if ($news->getSize()) : ?>
    <?=$this->getChildHtml('jaro_mycript_search')?>
    <?=$this->getPagerHtml()?>
    <table class="data-table table table-striped" id="my-news-table">
        <colgroup>
            <col width="16">
            <col width="12">
            <col width="12">
            <col width="250">
            <col width="250">
            <col width="12">
            <col width="250">
            <col width="110">
        </colgroup>
        <thead>
        <tr class="first last">
            <th><?=Mage::helper('jaro_myscript')->__('ID')?></th>
            <th><?=Mage::helper('jaro_myscript')->__('Name')?></th>
            <th><?=Mage::helper('jaro_myscript')->__('Description')?></th>
            <th><?=Mage::helper('jaro_myscript')->__('Created At')?></th>
            <th><?=Mage::helper('jaro_myscript')->__('Updated At')?></th>
            <th><?=Mage::helper('jaro_myscript')->__('Active')?></th>
            <th><?=Mage::helper('jaro_myscript')->__('Author')?></th>
            <th><?=Mage::helper('jaro_myscript')->__('Action')?></th>
        </tr>
        </thead>
        <tbody>
        <?php
            foreach ($news as $newsItem) {
                echo $this->getChild('news.row')
                    ->setData('news_item', $newsItem)
                    ->toHtml();
            }
        ?>
        </tbody>
    </table>
    <?=$this->getPagerHtml()?>
    <script type="text/javascript">decorateTable('my-news-table');</script>
<?php else: ?>
    <p><?=Mage::helper('jaro_myscript')->__('There is no news available.')?></p>
<?php endif ?>

