<?php $parameters = $this->getRequest()->getParams();?>
<?php $value = isset($parameters['search']) ? $parameters['search'] : ''?>
<form id="events-search" method="get" action="<?=$this->getMainUrl()?>">
    <div>
        <label>
            <?=Mage::helper('jaro_myscript')->__('Browser')?>
            <input class="search" type="text" name="search" autocomplete="off"
               <?php if ($this->isSearchAvailable($parameters)) :?>
                value="<?=$value?>"
               <?php else : ?>
                placeholder="<?=Mage::helper('jaro_myscript')->__('Search')?>"
               <?php endif?>
            >
        </label>
        <?php foreach ($parameters as $key => $parameter) :?>
            <?php if ($key !== 'search') :?>
                <input type="hidden" name="<?=$key?>" value="<?=$parameter?>">
            <?php endif ?>
        <?php endforeach;?>
        <input type="submit" value="<?=Mage::helper('jaro_myscript')->__('Search')?>">
    </div>
</form>