<?php $newsItem = Mage::registry('jaro_myscript_news_item'); ?>
<div class="page-title">
    <h1><?=Mage::helper('jaro_myscript')->__('News Item')?></h1>
</div>
<table class="data-table table table-striped" id="my-news-table">
    <colgroup>
        <col width="1">
        <col width="30">
        <col width="30">
        <col width="200">
        <col width="1">
        <col width="1">
    </colgroup>
    <thead>
        <tr class="first last">
            <th><?=Mage::helper('jaro_myscript')->__('ID')?></th>
            <th><?=Mage::helper('jaro_myscript')->__('Name')?></th>
            <th><?=Mage::helper('jaro_myscript')->__('Description')?></th>
            <th><?=Mage::helper('jaro_myscript')->__('Date')?></th>
            <th><?=Mage::helper('jaro_myscript')->__('Active')?></th>
            <th><?=Mage::helper('jaro_myscript')->__('Author')?></th>
        </tr>
    </thead>
    <tbody>
    <tr>
        <td><?=$newsItem->getNewsId()?></td>
        <td><?=$newsItem->getName()?></td>
        <td><?=$newsItem->getDescription()?></td>
        <td><?=Mage::helper('core')->formatDate($newsItem->getCreatedAt(), 'yyyy-MM-dd')?></td>
        <td><?=$this->getYesNoOption($newsItem->getIsActive())?></td>
        <td><?=$newsItem->getEmail()?></td>
    </tr>
    </tbody>
</table>
<script type="text/javascript">decorateTable('my-news-table');</script>