<?php
/** @var $this Mage_Customer_Block_Form_Login */
?>
<div class="workbench">
    <h1><?php echo $this->__('Login Form') ?></h1>
</div>
<div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8 <?php if (!empty($this->getMessagesBlock()->toHtml())): ?>alert alert-danger<?php endif; ?>">
        <?php echo $this->getMessagesBlock()->toHtml() ?>
    </div>
    <div class="col-md-2"></div>
</div>
<div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
        <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="login-form">
            <?php echo $this->getBlockHtml('formkey'); ?>

            <div class="form-group" style="position: static;">
                <label for="email" class="required"><?php echo $this->__('Login') ?></label>
                <input id="email type="text" name="login[username]" value="<?php echo $this->escapeHtml($this->getUsername()) ?>" class="form-control required-entry validate-email" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Enter login')) ?>" />
                <p class="help-block">Enter login...</p>
            </div>

            <div class="form-group" style="position: static;">
                <label for="pass" class="required"><?php echo $this->__('Password') ?></label>
                <input id="pass" type="password" name="login[password]" class="form-control input-text required-entry validate-password" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Password')) ?>" />
                <p class="help-block">Enter password.</p>
            </div>

            <div class="form-group" style="padding-right: 20px; position: static;">
                <button type="submit" class="btn btn-primary" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Login')) ?>" name="send" id="send2"><?php echo $this->__('Login') ?></button>
            </div>
            <?php echo $this->getChildHtml('form.additional.info'); ?>
            <?php echo $this->getChildHtml('persistent.remember.me'); ?>
            <?php echo $this->getChildHtml('persistent.remember.me.tooltip'); ?>
            <?php if (Mage::helper('checkout')->isContextCheckout()): ?>
                <input name="context" type="hidden" value="checkout" />
            <?php endif; ?>
        </form>
        <script type="text/javascript">
            //<![CDATA[
            var dataForm = new VarienForm('login-form', true);
            //]]>
        </script>
    </div>
    <div class="col-md-2"></div>
</div>